name: $(Build.BuildId)

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

jobs:
- job: MultiBuildCompile
  timeoutInMinutes: 0
  pool: HOD-DOCKER
  steps:
  - template: 05_MultiVersion_template.yml
    parameters:
      artifacttypes: ['Sandbox','OnPrem']
      artifactversions : ['16.3','16.4']
      artifactcountries: ['w1','be']