name: $(Build.BuildId)

pool: HOD-DOCKER

trigger: none

variables:
- group: Secrets

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder
# If you have a previous-app in your repo (and referred to it in your AppSourceCop.json, it will find it)

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: 'dk'
    appversiontemplate: '1.0.*.0'